function ch(n, title, description) {
  return { title, meta: `Chapter ${n}`, description };
}

function subj(name, icon, description, chapters) {
  return { name, icon, description, chapters };
}

export const extraClassPages = {
  'Class 10': {
    number: '10',
    title: 'Class 10',
    subtitle: 'Board exam notes with chapter-wise questions and PDFs.',
    info: 'NCERT-aligned study materials for every subject',
    subjects: [
      subj('Mathematics', 'fas fa-calculator', 'Algebra, trigonometry, geometry, mensuration, statistics, and probability.', [
        ch(1, 'Real Numbers', 'Euclid’s division lemma, HCF, LCM, and the fundamental theorem of arithmetic.'),
        ch(2, 'Polynomials', 'Zeros of a polynomial, relationship between zeros and coefficients, and division algorithm.'),
        ch(3, 'Pair of Linear Equations', 'Graphical and algebraic methods to solve two linear equations in two variables.'),
        ch(4, 'Quadratic Equations', 'Standard form, factorisation, quadratic formula, and nature of roots.'),
        ch(5, 'Arithmetic Progressions', 'nth term, sum of n terms, and applications of A.P. in daily life.'),
        ch(6, 'Triangles', 'Similar triangles, basic proportionality theorem, and Pythagoras theorem.'),
        ch(7, 'Coordinate Geometry', 'Distance formula, section formula, and area of a triangle.'),
        ch(8, 'Introduction to Trigonometry', 'Trigonometric ratios, identities, and values of standard angles.'),
        ch(9, 'Applications of Trigonometry', 'Heights and distances using trigonometric ratios.'),
        ch(10, 'Circles', 'Tangents to a circle and the number of tangents from a point.'),
        ch(11, 'Areas Related to Circles', 'Area of sectors, segments, and combinations of plane figures.'),
        ch(12, 'Surface Areas and Volumes', 'Surface area and volume of combinations of solids.'),
        ch(13, 'Statistics', 'Mean, median, mode of grouped data, and cumulative frequency graphs.'),
        ch(14, 'Probability', 'Classical probability, equally likely outcomes, and simple events.'),
      ]),
      subj('Physics', 'fas fa-atom', 'Light, human eye, electricity, magnetism, and sources of energy.', [
        ch(1, 'Light – Reflection', 'Laws of reflection, spherical mirrors, mirror formula, and magnification.'),
        ch(2, 'Light – Refraction', 'Refraction through lenses, lens formula, power of a lens, and refractive index.'),
        ch(3, 'Human Eye and Colourful World', 'Structure of the eye, defects of vision, dispersion, and atmospheric refraction.'),
        ch(4, 'Electricity', "Electric current, potential difference, Ohm's law, resistance, and electric power."),
        ch(5, 'Magnetic Effects of Electric Current', 'Magnetic field, Fleming’s left-hand rule, electric motor, and electromagnetic induction.'),
        ch(6, 'Sources of Energy', 'Conventional and non-conventional sources, and environmental consequences.'),
        ch(7, 'Heat', 'Temperature, heat transfer, and effects of heat in daily life.'),
        ch(8, 'Waves', 'Types of waves, characteristics of sound waves, and applications.'),
      ]),
      subj('Chemistry', 'fas fa-flask', 'Chemical reactions, acids and bases, metals, and carbon compounds.', [
        ch(1, 'Chemical Reactions and Equations', 'Types of reactions, balancing equations, oxidation, and reduction.'),
        ch(2, 'Acids, Bases and Salts', 'pH, indicators, important salts, and their uses in daily life.'),
        ch(3, 'Metals and Non-metals', 'Physical and chemical properties, reactivity series, and extraction of metals.'),
        ch(4, 'Carbon and its Compounds', 'Covalent bonding, homologous series, ethanol, ethanoic acid, and soaps.'),
        ch(5, 'Periodic Classification of Elements', 'Modern periodic table, trends in properties, and valency.'),
        ch(6, 'Chemical Bonding', 'Ionic and covalent bonds, and how atoms combine to form compounds.'),
      ]),
      subj('Biology', 'fas fa-dna', 'Life processes, reproduction, heredity, and our environment.', [
        ch(1, 'Life Processes', 'Nutrition, respiration, transportation, and excretion in plants and animals.'),
        ch(2, 'Control and Coordination', 'Nervous system, reflex action, hormones in animals, and plant hormones.'),
        ch(3, 'How do Organisms Reproduce?', 'Asexual and sexual reproduction, and reproductive health.'),
        ch(4, 'Heredity', 'Mendel’s experiments, traits, sex determination, and variation.'),
        ch(5, 'Our Environment', 'Ecosystems, food chains, ozone layer, and waste management.'),
        ch(6, 'Management of Natural Resources', 'Forests, wildlife, water, coal, and petroleum conservation.'),
      ]),
      subj('English', 'fas fa-language', 'First Flight and Footprints Without Feet — prose, poetry, and grammar.', [
        ch(1, 'A Letter to God', 'Faith, kindness, and irony in Lencho’s letter to God.'),
        ch(2, 'Nelson Mandela: Long Walk to Freedom', 'Apartheid, freedom, and Mandela’s inauguration speech.'),
        ch(3, 'Two Stories about Flying', 'Courage, fear, and the first flight of a young seagull.'),
        ch(4, 'From the Diary of Anne Frank', 'Anne’s diary, loneliness, and life during war.'),
        ch(5, 'Glimpses of India', 'Coorg, Assam tea, and Goan bakers — culture and travel.'),
        ch(6, 'The Necklace', 'Ambition, pride, and the twist in Maupassant’s story.'),
      ]),
      subj('Hindi', 'fas fa-book', 'क्षितिज, स्पर्श, और व्याकरण — Class 10 Hindi notes.', [
        ch(1, 'सूरदास', 'सूरदास के पद — भक्ति, वात्सल्य, और काव्य सौंदर्य।'),
        ch(2, 'नेताजी का चश्मा', 'स्वतंत्रता संग्राम की स्मृति और व्यंग्य पर आधारित कहानी।'),
        ch(3, 'बड़े भाई साहब', 'प्रेमचंद की कहानी — पढ़ाई, अनुभव, और भाईचारे का संदेश।'),
        ch(4, 'व्याकरण: वाक्य एवं रचना', 'वाक्य भेद, रचना, और परीक्षा के लिए महत्वपूर्ण उदाहरण।'),
      ]),
      subj('History', 'fas fa-landmark', 'India and the Contemporary World — nationalism and global history.', [
        ch(1, 'The Rise of Nationalism in Europe', 'French Revolution, nation-states, and unification of Germany and Italy.'),
        ch(2, 'Nationalism in India', 'Non-Cooperation, Civil Disobedience, and the making of a nation.'),
        ch(3, 'The Making of a Global World', 'Trade, colonialism, and the world economy before 1945.'),
        ch(4, 'The Age of Industrialisation', 'Factories, industrial change in India, and the role of workers.'),
        ch(5, 'Print Culture and the Modern World', 'Printing press, books, newspapers, and social reform.'),
      ]),
      subj('Geography', 'fas fa-globe-americas', 'Contemporary India — resources, agriculture, and manufacturing.', [
        ch(1, 'Resources and Development', 'Types of resources, resource planning, and soil conservation.'),
        ch(2, 'Forest and Wildlife Resources', 'Biodiversity, conservation, and types of forests in India.'),
        ch(3, 'Water Resources', 'Water scarcity, multipurpose projects, and rainwater harvesting.'),
        ch(4, 'Agriculture', 'Types of farming, major crops, and technological reforms.'),
        ch(5, 'Minerals and Energy Resources', 'Metallic and non-metallic minerals, and conventional energy sources.'),
        ch(6, 'Manufacturing Industries', 'Types of industries, industrial pollution, and location factors.'),
        ch(7, 'Lifelines of National Economy', 'Roadways, railways, waterways, airways, and international trade.'),
      ]),
      subj('Political Science', 'fas fa-balance-scale', 'Democratic Politics — power sharing, parties, and outcomes of democracy.', [
        ch(1, 'Power Sharing', 'Belgium and Sri Lanka, forms of power sharing, and why it is desirable.'),
        ch(2, 'Federalism', 'Features of federalism, India as a federal country, and decentralisation.'),
        ch(3, 'Gender, Religion and Caste', 'Social divisions in politics and the idea of communalism.'),
        ch(4, 'Political Parties', 'Functions, national and state parties, and challenges to political parties.'),
        ch(5, 'Outcomes of Democracy', 'Accountability, economic growth, inequality, and dignity.'),
      ]),
      subj('Economics', 'fas fa-coins', 'Development, sectors of the economy, money, and globalisation.', [
        ch(1, 'Development', 'National income, per capita income, HDI, and sustainable development.'),
        ch(2, 'Sectors of the Indian Economy', 'Primary, secondary, tertiary sectors, and organised vs unorganised workers.'),
        ch(3, 'Money and Credit', 'Modern forms of money, banks, credit, and self-help groups.'),
        ch(4, 'Globalisation and the Indian Economy', 'MNCs, liberalisation, WTO, and impact on Indian producers.'),
        ch(5, 'Consumer Rights', 'Consumer movement, COPRA, and the right to information.'),
      ]),
      subj('Computer Applications', 'fas fa-laptop-code', 'Internet, HTML, cybersecurity, and databases for Class 10.', [
        ch(1, 'Internet Basics', 'WWW, browsers, search engines, and email.'),
        ch(2, 'HTML', 'Tags, links, images, tables, and creating simple web pages.'),
        ch(3, 'Cyber Ethics', 'Netiquette, intellectual property, and safe digital behaviour.'),
        ch(4, 'Databases', 'Tables, records, and basic SQL ideas for school projects.'),
      ]),
    ],
  },
  'Class 11': {
    number: '11',
    title: 'Class 11',
    subtitle: 'Science, Commerce, and Arts notes for Class 11.',
    info: 'Streams: Science • Commerce • Arts',
    subjects: [
      subj('Mathematics', 'fas fa-calculator', 'Sets, relations, functions, calculus basics, and statistics.', [
        ch(1, 'Sets', 'Types of sets, Venn diagrams, union, intersection, and complement.'),
        ch(2, 'Relations and Functions', 'Ordered pairs, domain, range, and types of functions.'),
        ch(3, 'Trigonometric Functions', 'Radian measure, identities, and trigonometric equations.'),
        ch(4, 'Complex Numbers', 'Algebra of complex numbers, polar form, and quadratic equations.'),
        ch(5, 'Linear Inequalities', 'Algebraic solutions and graphical representation of inequalities.'),
        ch(6, 'Permutations and Combinations', 'Fundamental principle of counting, nPr, and nCr.'),
        ch(7, 'Binomial Theorem', 'Binomial expansion and general term.'),
        ch(8, 'Sequences and Series', 'A.P., G.P., and special series.'),
        ch(9, 'Straight Lines', 'Slope, various forms of a line, and distance of a point from a line.'),
        ch(10, 'Conic Sections', 'Circle, parabola, ellipse, and hyperbola.'),
        ch(11, 'Limits and Derivatives', 'Idea of a limit and derivative as a rate of change.'),
        ch(12, 'Statistics and Probability', 'Mean deviation, variance, and random experiments.'),
      ]),
      subj('Physics', 'fas fa-atom', 'Mechanics, gravitation, thermodynamics, oscillations, and waves.', [
        ch(1, 'Units and Measurements', 'SI units, significant figures, dimensions, and errors.'),
        ch(2, 'Motion in a Straight Line', 'Position, velocity, acceleration, and kinematic equations.'),
        ch(3, 'Motion in a Plane', 'Vectors, projectile motion, and uniform circular motion.'),
        ch(4, 'Laws of Motion', "Newton's laws, friction, circular motion, and conservation of momentum."),
        ch(5, 'Work, Energy and Power', 'Work-energy theorem, conservative forces, and collisions.'),
        ch(6, 'System of Particles and Rotational Motion', 'Centre of mass, torque, angular momentum, and moment of inertia.'),
        ch(7, 'Gravitation', "Kepler's laws, acceleration due to gravity, and satellites."),
        ch(8, 'Mechanical Properties of Solids', 'Stress, strain, Hooke’s law, and elastic moduli.'),
        ch(9, 'Mechanical Properties of Fluids', 'Pressure, Pascal’s law, viscosity, and Bernoulli’s principle.'),
        ch(10, 'Thermal Properties of Matter', 'Heat, temperature, expansion, and calorimetry.'),
        ch(11, 'Thermodynamics', 'Zeroth, first and second laws, and heat engines.'),
        ch(12, 'Oscillations and Waves', 'SHM, damped oscillations, and progressive waves.'),
      ]),
      subj('Chemistry', 'fas fa-flask', 'Basic concepts, atomic structure, bonding, states of matter, and organic chemistry.', [
        ch(1, 'Some Basic Concepts of Chemistry', 'Mole concept, stoichiometry, and laws of chemical combination.'),
        ch(2, 'Structure of Atom', 'Bohr model, quantum numbers, and electronic configuration.'),
        ch(3, 'Classification of Elements', 'Periodic table, periodic trends, and valency.'),
        ch(4, 'Chemical Bonding', 'Ionic, covalent, VSEPR, hybridisation, and molecular orbital theory basics.'),
        ch(5, 'Thermodynamics', 'Enthalpy, entropy, Gibbs energy, and Hess’s law.'),
        ch(6, 'Equilibrium', 'Chemical equilibrium, Le Chatelier’s principle, and pH.'),
        ch(7, 'Redox Reactions', 'Oxidation number, balancing redox equations, and electrochemistry intro.'),
        ch(8, 'Organic Chemistry – Basic Principles', 'IUPAC names, isomerism, and reaction mechanisms.'),
        ch(9, 'Hydrocarbons', 'Alkanes, alkenes, alkynes, and aromatic compounds.'),
      ]),
      subj('Biology', 'fas fa-dna', 'Diversity of living organisms, plant physiology, and human physiology.', [
        ch(1, 'The Living World', 'What is living, biodiversity, and taxonomic categories.'),
        ch(2, 'Biological Classification', 'Five kingdom classification and viruses.'),
        ch(3, 'Plant Kingdom', 'Algae, bryophytes, pteridophytes, gymnosperms, and angiosperms.'),
        ch(4, 'Animal Kingdom', 'Basis of classification and major animal phyla.'),
        ch(5, 'Morphology of Flowering Plants', 'Root, stem, leaf, inflorescence, and flower.'),
        ch(6, 'Cell: The Unit of Life', 'Cell organelles, prokaryotic and eukaryotic cells.'),
        ch(7, 'Biomolecules', 'Carbohydrates, proteins, lipids, nucleic acids, and enzymes.'),
        ch(8, 'Photosynthesis', 'Light reaction, Calvin cycle, and factors affecting photosynthesis.'),
        ch(9, 'Respiration in Plants', 'Glycolysis, Krebs cycle, and electron transport.'),
        ch(10, 'Human Physiology', 'Digestion, breathing, circulation, excretion, and neural control.'),
      ]),
      subj('English', 'fas fa-language', 'Hornbill and Snapshots — Class 11 English notes.', [
        ch(1, 'The Portrait of a Lady', 'Khushwant Singh’s grandmother — companionship, faith, and change.'),
        ch(2, "We're Not Afraid to Die", 'Courage, family, and survival at sea.'),
        ch(3, 'Discovering Tut', 'King Tut’s mummy, archaeology, and scientific investigation.'),
        ch(4, 'The Ailing Planet', 'Environment, sustainable development, and human responsibility.'),
        ch(5, 'The Summer of the Beautiful White Horse', 'Honesty, family honour, and childhood adventure.'),
        ch(6, 'The Address', 'War, memory, and a daughter’s visit after the Holocaust.'),
      ]),
      subj('Accountancy', 'fas fa-chart-line', 'Accounting principles, journal, ledger, and financial statements.', [
        ch(1, 'Introduction to Accounting', 'Meaning, objectives, and basic accounting terms.'),
        ch(2, 'Theory Base of Accounting', 'GAAP, accounting principles, and accounting standards.'),
        ch(3, 'Recording of Transactions', 'Source documents, journal, cash book, and ledger.'),
        ch(4, 'Bank Reconciliation Statement', 'Causes of difference and preparation of BRS.'),
        ch(5, 'Depreciation and Provisions', 'Methods of depreciation, reserves, and provisions.'),
        ch(6, 'Financial Statements', 'Trading account, profit and loss, and balance sheet.'),
      ]),
      subj('Business Studies', 'fas fa-briefcase', 'Nature of business, forms of organisation, and business services.', [
        ch(1, 'Nature and Purpose of Business', 'Economic activities, industry, commerce, and business objectives.'),
        ch(2, 'Forms of Business Organisation', 'Sole proprietorship, partnership, company, and cooperative society.'),
        ch(3, 'Public, Private and Global Enterprises', 'Departmental undertakings, PSUs, and MNCs.'),
        ch(4, 'Business Services', 'Banking, insurance, warehousing, and communication.'),
        ch(5, 'Emerging Modes of Business', 'E-business, outsourcing, and online transactions.'),
        ch(6, 'Social Responsibility of Business', 'Ethics, environment, and responsibility towards stakeholders.'),
      ]),
      subj('Economics', 'fas fa-coins', 'Statistics for economics and introductory microeconomics.', [
        ch(1, 'Introduction to Economics', 'What is economics, and why we study statistics in economics.'),
        ch(2, 'Collection of Data', 'Primary and secondary data, census, and sampling.'),
        ch(3, 'Organisation and Presentation of Data', 'Classification, tabulation, and diagrams.'),
        ch(4, 'Measures of Central Tendency', 'Mean, median, and mode.'),
        ch(5, 'Introduction to Microeconomics', 'Central problems of an economy and production possibility curve.'),
        ch(6, "Consumer's Equilibrium", 'Utility, indifference curve, and demand.'),
        ch(7, 'Production and Cost', 'Production function, returns to a factor, and cost curves.'),
        ch(8, 'Perfect Competition', 'Features, price determination, and revenue curves.'),
      ]),
      subj('History', 'fas fa-landmark', 'Themes in World History — early societies to changing cultural traditions.', [
        ch(1, 'Writing and City Life', 'Mesopotamia, urbanisation, and the invention of writing.'),
        ch(2, 'An Empire Across Three Continents', 'The Roman Empire, economy, and society.'),
        ch(3, 'The Three Orders', 'Feudal society in Western Europe.'),
        ch(4, 'Changing Cultural Traditions', 'Renaissance, humanism, and new ideas in Europe.'),
        ch(5, 'The Industrial Revolution', 'Factories, workers, and the making of industrial society.'),
        ch(6, 'Displacing Indigenous Peoples', 'Colonisation in America and Australia.'),
      ]),
      subj('Political Science', 'fas fa-balance-scale', 'Indian Constitution at work and political theory.', [
        ch(1, 'Constitution: Why and How', 'Making of the Constitution and its philosophy.'),
        ch(2, 'Rights in the Indian Constitution', 'Fundamental Rights, Directive Principles, and Fundamental Duties.'),
        ch(3, 'Election and Representation', 'Electoral system, Election Commission, and reserved constituencies.'),
        ch(4, 'Executive', 'President, Prime Minister, and the parliamentary executive.'),
        ch(5, 'Legislature', 'Parliament, law-making, and parliamentary control.'),
        ch(6, 'Judiciary', 'Independence of judiciary, judicial review, and PIL.'),
        ch(7, 'Political Theory: Liberty and Equality', 'Meaning of freedom, equality, and social justice.'),
      ]),
      subj('Computer Science', 'fas fa-laptop-code', 'Python programming, computational thinking, and computer systems.', [
        ch(1, 'Computer System Overview', 'Hardware, software, memory, and number systems.'),
        ch(2, 'Emerging Trends', 'AI, IoT, cloud computing, and big data.'),
        ch(3, 'Python Basics', 'Variables, data types, operators, and I/O.'),
        ch(4, 'Flow of Control', 'Conditionals, loops, and nested statements.'),
        ch(5, 'Strings and Lists', 'Indexing, slicing, and list operations.'),
        ch(6, 'Functions', 'User-defined functions, arguments, and scope.'),
      ]),
    ],
  },
  'Class 12': {
    number: '12',
    title: 'Class 12',
    subtitle: 'Board and entrance exam notes for Science, Commerce, and Arts.',
    info: 'Streams: Science • Commerce • Arts',
    subjects: [
      subj('Mathematics', 'fas fa-calculator', 'Relations, calculus, vectors, probability, and linear programming.', [
        ch(1, 'Relations and Functions', 'Types of relations, invertible functions, and binary operations.'),
        ch(2, 'Inverse Trigonometric Functions', 'Principal values, properties, and graphs.'),
        ch(3, 'Matrices', 'Types of matrices, operations, and invertible matrices.'),
        ch(4, 'Determinants', 'Properties, adjoint, inverse, and solving linear equations.'),
        ch(5, 'Continuity and Differentiability', 'Continuity, derivatives of composite and inverse functions.'),
        ch(6, 'Application of Derivatives', 'Rate of change, maxima and minima, and tangents.'),
        ch(7, 'Integrals', 'Indefinite and definite integrals, and methods of integration.'),
        ch(8, 'Application of Integrals', 'Area under curves.'),
        ch(9, 'Differential Equations', 'Order, degree, and solutions of first-order equations.'),
        ch(10, 'Vector Algebra', 'Dot product, cross product, and scalar triple product.'),
        ch(11, 'Three Dimensional Geometry', 'Direction cosines, lines, and planes.'),
        ch(12, 'Probability', 'Conditional probability, Bayes’ theorem, and random variables.'),
      ]),
      subj('Physics', 'fas fa-atom', 'Electrostatics, current electricity, magnetism, optics, and modern physics.', [
        ch(1, 'Electric Charges and Fields', 'Coulomb’s law, electric field, and Gauss’s theorem.'),
        ch(2, 'Electrostatic Potential and Capacitance', 'Potential, capacitors, and energy stored.'),
        ch(3, 'Current Electricity', "Ohm's law, Kirchhoff’s rules, and electrical instruments."),
        ch(4, 'Moving Charges and Magnetism', 'Biot–Savart law, Ampere’s law, and force on a current.'),
        ch(5, 'Magnetism and Matter', 'Bar magnet, Earth’s magnetism, and magnetic materials.'),
        ch(6, 'Electromagnetic Induction', 'Faraday’s law, Lenz’s law, and self and mutual induction.'),
        ch(7, 'Alternating Current', 'AC circuits, resonance, and transformers.'),
        ch(8, 'Electromagnetic Waves', 'Displacement current and the electromagnetic spectrum.'),
        ch(9, 'Ray Optics', 'Reflection, refraction, lenses, and optical instruments.'),
        ch(10, 'Wave Optics', 'Huygens principle, interference, diffraction, and polarisation.'),
        ch(11, 'Dual Nature of Radiation and Matter', 'Photoelectric effect and de Broglie waves.'),
        ch(12, 'Atoms, Nuclei and Semiconductors', 'Bohr model, radioactivity, and p-n junction diodes.'),
      ]),
      subj('Chemistry', 'fas fa-flask', 'Solutions, electrochemistry, organic compounds, and biomolecules.', [
        ch(1, 'Solutions', 'Concentration terms, Raoult’s law, and colligative properties.'),
        ch(2, 'Electrochemistry', 'Electrochemical cells, Nernst equation, and corrosion.'),
        ch(3, 'Chemical Kinetics', 'Rate of reaction, order, and Arrhenius equation.'),
        ch(4, 'd and f Block Elements', 'Transition metals, lanthanoids, and important compounds.'),
        ch(5, 'Coordination Compounds', 'Werner’s theory, IUPAC names, and bonding.'),
        ch(6, 'Haloalkanes and Haloarenes', 'Nomenclature, reactions, and uses.'),
        ch(7, 'Alcohols, Phenols and Ethers', 'Preparation, properties, and important reactions.'),
        ch(8, 'Aldehydes, Ketones and Carboxylic Acids', 'Nucleophilic addition and acidity of carboxylic acids.'),
        ch(9, 'Amines', 'Classification, basicity, and diazonium salts.'),
        ch(10, 'Biomolecules', 'Carbohydrates, proteins, vitamins, and nucleic acids.'),
      ]),
      subj('Biology', 'fas fa-dna', 'Reproduction, genetics, evolution, biotechnology, and ecology.', [
        ch(1, 'Sexual Reproduction in Flowering Plants', 'Flower structure, pollination, fertilisation, and seed formation.'),
        ch(2, 'Human Reproduction', 'Male and female reproductive systems, and pregnancy.'),
        ch(3, 'Reproductive Health', 'Family planning, STDs, and infertility.'),
        ch(4, 'Principles of Inheritance and Variation', 'Mendelian genetics, sex determination, and genetic disorders.'),
        ch(5, 'Molecular Basis of Inheritance', 'DNA, replication, transcription, translation, and Human Genome Project.'),
        ch(6, 'Evolution', 'Origin of life, Darwinism, and Hardy–Weinberg principle.'),
        ch(7, 'Human Health and Disease', 'Immunity, AIDS, cancer, and drugs.'),
        ch(8, 'Biotechnology', 'Principles, processes, and applications of biotechnology.'),
        ch(9, 'Organisms and Populations', 'Habitat, population growth, and interactions.'),
        ch(10, 'Ecosystem and Biodiversity', 'Energy flow, ecological pyramids, and conservation.'),
      ]),
      subj('English', 'fas fa-language', 'Flamingo and Vistas — Class 12 English notes.', [
        ch(1, 'The Last Lesson', 'Language, patriotism, and the last French lesson in Alsace.'),
        ch(2, 'Lost Spring', 'Poverty, child labour, and stories from Firozabad and Seemapuri.'),
        ch(3, 'Deep Water', 'Overcoming fear of water through practice and determination.'),
        ch(4, 'The Rattrap', 'Kindness, redemption, and the metaphor of the world as a rattrap.'),
        ch(5, 'Indigo', 'Gandhi, Champaran, and the fight for sharecroppers.'),
        ch(6, 'The Third Level', 'Time, escape, and the third level at Grand Central Station.'),
      ]),
      subj('Accountancy', 'fas fa-chart-line', 'Partnership, companies, and analysis of financial statements.', [
        ch(1, 'Accounting for Partnership', 'Profit sharing, capital accounts, and past adjustments.'),
        ch(2, 'Reconstitution of Partnership', 'Admission, retirement, and death of a partner.'),
        ch(3, 'Dissolution of Partnership Firm', 'Settlement of accounts and realisation account.'),
        ch(4, 'Accounting for Share Capital', 'Issue of shares, forfeiture, and reissue.'),
        ch(5, 'Issue of Debentures', 'Types of debentures and their issue.'),
        ch(6, 'Financial Statement Analysis', 'Comparative statements, ratios, and cash flow statement.'),
      ]),
      subj('Business Studies', 'fas fa-briefcase', 'Principles of management, marketing, and financial management.', [
        ch(1, 'Nature and Significance of Management', 'Functions, levels, and coordination.'),
        ch(2, 'Principles of Management', 'Fayol’s principles and Taylor’s scientific management.'),
        ch(3, 'Business Environment', 'Dimensions of environment and liberalisation.'),
        ch(4, 'Planning and Organising', 'Types of plans, organisation structure, and delegation.'),
        ch(5, 'Staffing and Directing', 'Recruitment, selection, motivation, and leadership.'),
        ch(6, 'Controlling', 'Process of control and relationship with planning.'),
        ch(7, 'Financial Management and Marketing', 'Capital structure, working capital, and marketing mix.'),
      ]),
      subj('Economics', 'fas fa-coins', 'Introductory macroeconomics and Indian economic development.', [
        ch(1, 'National Income Accounting', 'GDP, GNP, methods of calculating national income.'),
        ch(2, 'Money and Banking', 'Functions of money, RBI, and credit creation.'),
        ch(3, 'Determination of Income and Employment', 'Aggregate demand, multiplier, and excess demand.'),
        ch(4, 'Government Budget', 'Objectives, receipts, expenditure, and deficit.'),
        ch(5, 'Open Economy Macroeconomics', 'Foreign exchange, balance of payments, and exchange rate.'),
        ch(6, 'Indian Economy on the Eve of Independence', 'Colonial impact on agriculture, industry, and foreign trade.'),
        ch(7, 'Liberalisation, Privatisation and Globalisation', '1991 reforms and their impact.'),
        ch(8, 'Human Capital and Rural Development', 'Education, health, credit, and rural development programmes.'),
      ]),
      subj('History', 'fas fa-landmark', 'Themes in Indian History — from Harappa to modern India.', [
        ch(1, 'Bricks, Beads and Bones', 'Harappan civilisation, towns, craft, and decline.'),
        ch(2, 'Kings, Farmers and Towns', 'Mahajanapadas, Mauryas, and early historic cities.'),
        ch(3, 'Kinship, Caste and Class', 'Social history from the Mahabharata.'),
        ch(4, 'Thinkers, Beliefs and Buildings', 'Buddhism, Jainism, and architecture.'),
        ch(5, 'Colonialism and the Countryside', 'Revenue systems and rural society under colonial rule.'),
        ch(6, 'Rebels and the Raj', 'The revolt of 1857 and its representation.'),
        ch(7, 'Mahatma Gandhi and the Nationalist Movement', 'Satyagraha, mass nationalism, and independence.'),
      ]),
      subj('Political Science', 'fas fa-balance-scale', 'Contemporary world politics and politics in India since independence.', [
        ch(1, 'The End of Bipolarity', 'Disintegration of the Soviet Union and a new world order.'),
        ch(2, 'Contemporary Centres of Power', 'EU, ASEAN, China, and emerging powers.'),
        ch(3, 'United Nations and its Organisations', 'UN organs, reform, and India’s claim for a permanent seat.'),
        ch(4, 'Challenges of Nation-Building', 'Partition, integration of princely states, and reorganisation of states.'),
        ch(5, 'Politics of Planned Development', 'Planning Commission, mixed economy, and land reforms.'),
        ch(6, 'India’s External Relations', 'Non-alignment, wars, and nuclear policy.'),
        ch(7, 'Regional Aspirations', 'Kashmir, Punjab, North-East, and accommodation of diversity.'),
      ]),
      subj('Computer Science', 'fas fa-laptop-code', 'Python revision, data structures, SQL, and computer networks.', [
        ch(1, 'Python Revision Tour', 'Functions, file handling, and exception handling.'),
        ch(2, 'Data Structures', 'Stacks, queues, and operations using lists.'),
        ch(3, 'Computer Networks', 'LAN, WAN, protocols, and network devices.'),
        ch(4, 'SQL', 'DDL, DML, joins, and aggregate functions.'),
        ch(5, 'Interface Python with SQL', 'Connecting Python programs with a database.'),
      ]),
    ],
  },
  Graduation: {
    number: '🎓',
    title: 'Graduation',
    subtitle: 'Degree-level notes for B.A., B.Sc., B.Com., BCA, and BBA.',
    info: 'Courses: B.A. • B.Sc. • B.Com. • BCA • BBA',
    subjects: [
      subj('B.A.', 'fas fa-book-open', 'Arts papers — English, history, political science, and sociology.', [
        ch(1, 'English Literature', 'Poetry, drama, fiction, and literary criticism basics.'),
        ch(2, 'Indian History', 'Ancient, medieval, and modern India for undergraduate study.'),
        ch(3, 'Political Science', 'Political theory, comparative politics, and Indian government.'),
        ch(4, 'Sociology', 'Society, social change, caste, class, and research methods.'),
        ch(5, 'Economics (Optional)', 'Microeconomics, macroeconomics, and Indian economy.'),
      ]),
      subj('B.Sc.', 'fas fa-flask', 'Science papers — physics, chemistry, mathematics, and biology.', [
        ch(1, 'Physics', 'Mechanics, electrodynamics, optics, and modern physics.'),
        ch(2, 'Chemistry', 'Inorganic, organic, and physical chemistry for B.Sc.'),
        ch(3, 'Mathematics', 'Calculus, algebra, differential equations, and linear algebra.'),
        ch(4, 'Botany', 'Plant diversity, physiology, genetics, and ecology.'),
        ch(5, 'Zoology', 'Animal diversity, physiology, cell biology, and evolution.'),
      ]),
      subj('B.Com.', 'fas fa-chart-line', 'Commerce papers — accounts, business law, tax, and economics.', [
        ch(1, 'Financial Accounting', 'Partnership, company accounts, and financial statements.'),
        ch(2, 'Business Law', 'Indian Contract Act, companies, and consumer protection.'),
        ch(3, 'Corporate Accounting', 'Share capital, amalgamation, and holding companies.'),
        ch(4, 'Income Tax', 'Heads of income, deductions, and basic computation.'),
        ch(5, 'Cost Accounting', 'Material, labour, overheads, and costing methods.'),
        ch(6, 'Business Economics', 'Demand, production, markets, and national income.'),
      ]),
      subj('BCA', 'fas fa-laptop-code', 'Computer applications — programming, DBMS, web, and networks.', [
        ch(1, 'Programming in C / C++', 'Data types, control flow, functions, arrays, and OOP basics.'),
        ch(2, 'Data Structures', 'Arrays, linked lists, stacks, queues, trees, and sorting.'),
        ch(3, 'Database Management Systems', 'ER model, SQL, normalisation, and transactions.'),
        ch(4, 'Web Technologies', 'HTML, CSS, JavaScript, and introductory backend ideas.'),
        ch(5, 'Operating Systems', 'Processes, memory management, file systems, and scheduling.'),
        ch(6, 'Computer Networks', 'OSI model, TCP/IP, IP addressing, and network security.'),
      ]),
      subj('BBA', 'fas fa-briefcase', 'Business administration — management, marketing, HR, and finance.', [
        ch(1, 'Principles of Management', 'Planning, organising, staffing, directing, and controlling.'),
        ch(2, 'Marketing Management', 'Marketing mix, consumer behaviour, and branding.'),
        ch(3, 'Human Resource Management', 'Recruitment, training, performance appraisal, and labour laws.'),
        ch(4, 'Financial Management', 'Capital budgeting, working capital, and financial statements.'),
        ch(5, 'Organisational Behaviour', 'Motivation, leadership, group behaviour, and organisational culture.'),
        ch(6, 'Business Communication', 'Reports, presentations, emails, and professional writing.'),
      ]),
    ],
  },
};
